config/routes.rb
JelloPan::Application.routes.draw do
 
  resources :events
  
  root :to => "events#index"

end

app/models/event.rb
class Event < ActiveRecord::Base
  default_scope { order(event_date: :desc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
    @album_suggestions = [
      "\"The Party Album!\" by Vengaboys",
      "\"The Platinum Album\" by Vengaboys",
      "\"Xmas Party Album\" by Vengaboys",
    ]
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.create(event_params)
    if @event.save
      redirect_to root_url
    else
      flash.now[:error] = '3rr0r'
      render 'new'
    end
  end

  def show
    redirect_to edit_event_path(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    event = Event.find(params[:id])
    event.update_attributes!(event_params)
    redirect_to root_url
  end

  def destroy
    @event = Event.find(params[:id]).destroy
    flash[:success] = "event deleted"
    redirect_to root_url
  end

  private
    def event_params
      params.require(:event).permit(:album, :event_date, :host, :ingredient)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= render "shared/error_messages", :target => @event %>

<p>
  <%= form.label :album %><br />
  <%= form.text_field :album %>
</p>
<p>
  <%= form.label :host %><br />
  <%= form.text_field :host %>
</p>
<p>
  <%= form.label :ingredient %><br />
  <%= form.text_field :ingredient %>
</p>
<p>
  <%= form.label :event_date %><br />
  <%= form.date_select :event_date %>
</p>

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<%= form_for @event, :url => event_path do |f| %>
  <%= render :partial => "form", :object => f, :locals => { :event => @event } %>
  <%= f.submit "Update" %>
<% end %>

app/views/events/index.html.erb
<h2> JelloPan Events </h2>

<ul>
<% @events.each do |event| %>
  <li><b><%= event.host %></b> hosted JelloPan on <b><%= event.event_date.strftime("%B %d, %Y") %></b> playing the album <b><%= event.album %></b> with the secret ingredient <b><%= event.ingredient %></b>
  <%= link_to "edit", edit_event_path(event.id) %>
  <%= link_to "delete", event, method: :delete,
                               data: { confirm: "You sure?" },
                               title: event.album %>
  </li>
<% end %>
</ul>

<%= link_to 'Add Event', new_event_path, :class => "btn" %>

<br>

Looking for an album suggestion? How about <%= @album_suggestions.sample %>

app/views/events/new.html.erb
<%= form_for @event do |f| %>
  <%= render :partial => "form", :object => f, :locals => { :event => @event } %>
  <%= f.submit "Add Event" %>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "JelloPan!", root_path, :class => 'brand' %>
<ul class="nav">
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "JelloPan" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
          <%= render 'layouts/messages' %>
          <%= yield %>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(target.errors.count, "error") %> prohibited this record from being saved:</h2>
    <ul>
      <% target.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul> 
  </div>
<% end %>